Задача 1
Даны значения зарплат из выборки выпускников: 

100, 80, 75, 77, 89, 33, 45, 25, 65, 17, 30, 24, 57, 55, 70, 75, 65, 84, 90, 150

Без использования статистических функций вроде mean, std, var, посчитать среднее арифметическое, среднее квадратичное отклонение, смещенную и несмещенную оценки дисперсий для данной выборки.
Можно затем посчитать те же значения с использованием статистических функций, чтобы проверить себя.

In [1]:
import numpy as np
import math
a = np.array([100, 80, 75, 77, 89, 33, 45, 25, 65, 17, 30, 24, 57, 55, 70, 75, 65, 84, 90, 150])

In [2]:
quantity = len(a)
quantity

20

In [3]:
summ = np.sum(a)
summ

1306

In [4]:
mean_= summ / quantity
mean_

65.3

In [5]:
np.mean(a)

65.3

In [6]:
#смещенная дисперсия
sigma = 0
for i in a:
    sigma += (i - mean_)**2
var_= sigma / quantity
var_

950.11

In [7]:
np.var(a, ddof=0)

950.11

In [8]:
#несмещенная дисперсия
var_nonoffset = sigma / (quantity - 1)
var_nonoffset

1000.1157894736842

In [9]:
np.var(a, ddof=1)

1000.1157894736842

In [10]:
std_ = math.sqrt(var_)
std_

30.823854398825596

In [11]:
np.std(a)

30.823854398825596

Задача 2
Для выборки из задачи 1 найти первый и третий квартили, интерквартильное расстояние. Найти выборсы в выборке, используя для этого "усы" из boxplot. В этой задаче можно использовать статистические функции.

In [12]:
np.sort(a)

array([ 17,  24,  25,  30,  33,  45,  55,  57,  65,  65,  70,  75,  75,
        77,  80,  84,  89,  90, 100, 150])

In [13]:
print(np.quantile(a, 0.25))
np.sort(a[(a < np.quantile(a, 0.25))])

42.0


array([17, 24, 25, 30, 33])

In [14]:
print(np.quantile(a, 0.75))
np.sort(a[(a < np.quantile(a, 0.75))])

81.0


array([17, 24, 25, 30, 33, 45, 55, 57, 65, 65, 70, 75, 75, 77, 80])

In [15]:
Interquartile = a[(a > np.quantile(a, 0.25)) & (a < np.quantile(a, 0.75))]
np.sort(Interquartile)

array([45, 55, 57, 65, 65, 70, 75, 75, 77, 80])

Задача 3
Для распределения Пуассона с параметром a = 5 найти теоретические (т.е. используя закон распределения, а не выборку) мат. ожидание, моду и медиану.

In [16]:
a = 5 #это же и есть мат ожидание?

Задача 4
В университет на факультеты A и B поступило равное количество студентов, а на факультет C студентов поступило столько же, сколько на A и B вместе. Вероятность того, что студент факультета A сдаст первую сессию, равна 0.8. Для студента факультета B эта вероятность равна 0.7, а для студента факультета C - 0.9. Студент сдал первую сессию. Какова вероятность, что он учится: a) на факультете A? б) на факультете B? в) на факультете C?
Замечание: да, эта задача не на тему описательных статистик, но тема важная, и её стоит иногда освежать в памяти.

In [17]:
#допустим, что на факультетах А и В по 10 студентов
A, B = 10, 10
C = A + B
ABC = A + B + C #40
PA = 0.8
PB = 0.7
PC = 0.9

In [18]:
facA = (PA*A/ABC)/((PA*A/ABC)+(PB*B/ABC)+(PC*C/ABC))
facB = (PB*B/ABC)/((PA*A/ABC)+(PB*B/ABC)+(PC*C/ABC))
facC = (PC*C/ABC)/((PA*A/ABC)+(PB*B/ABC)+(PC*C/ABC))
print(facA, facB, facC)

0.24242424242424246 0.21212121212121213 0.5454545454545455
